#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// 如果使用 Duplex I2S 模式，请注释下面一行
#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_42
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_40
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_2

#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_16
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_17
// 功放使能引脚，在板子初始化时控制
#define AUDIO_I2S_SPK_GPIO_EN   GPIO_NUM_18

#else

#define AUDIO_I2S_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7

#endif

// 绿板 GPIO 定义
#define BOOT_BUTTON_GPIO        GPIO_NUM_0   // 绿板为0；紫板为1
#define TOUCH_BUTTON_GPIO       GPIO_NUM_5   // 自定义功能按键

#define SIMPLE_LED_GPIO         GPIO_NUM_8   // 简单LED
#define BUILTIN_LED_GPIO        GPIO_NUM_48  // 主LED

// 无显示屏配置
// #define DISPLAY_SDA_PIN      GPIO_NUM_41
// #define DISPLAY_SCL_PIN      GPIO_NUM_42

#endif // _BOARD_CONFIG_H_
